import { Slider } from "./Slider";
import React from "react";
import "./HomePage.css";
import  Navbar  from "../../Components/navbar/Navbar";
import Footer from "../../Components/footer/Footer"

const HomePage = () => {
  return (
    <>
    <Navbar/>
    <div><Slider/></div>
    <div className="header">
      <h2>Hottest On The Scene</h2></div>
      <div className="grid">
        <div>
          <img
            src="https://logan.nnnow.com/content/dam/nnnow-project/09-nov-2022/se-11-11-/p-storys/Smashbox_P-story.jpg"
            alt="ProductIMG"
          />
        </div>
        <div>
          <img
            src="https://logan.nnnow.com/content/dam/nnnow-project/09-nov-2022/se-11-11-/p-storys/Clinique_Pstory.jpg"
            alt="ProductIMG"
          />
        </div>
        <div>
          <img
            src="https://logan.nnnow.com/content/dam/nnnow-project/09-nov-2022/se-11-11-/p-storys/EsteeLauder_Pstory.jpg"
            alt="ProductIMG"
          />
        </div>
        <div>
          <img
            src="https://logan.nnnow.com/content/dam/nnnow-project/09-nov-2022/se-11-11-/p-storys/TOOFACED_Pstory.jpg"
            alt="ProductIMG"
          />
        </div>
        <div>
          <img
            src="https://logan.nnnow.com/content/dam/nnnow-project/09-nov-2022/se-11-11-/p-storys/opi_P-story.jpg"
            alt="ProductIMG"
          />
        </div>
        <div>
          <img
            src="https://logan.nnnow.com/content/dam/nnnow-project/09-nov-2022/se-11-11-/p-storys/ABH_P-story.jpg"
            alt="ProductIMG"
          />
        </div>
        <div>
          <img
            src="https://logan.nnnow.com/content/dam/nnnow-project/09-nov-2022/se-11-11-/p-storys/MUFE_P-story.jpg"
            alt="ProductIMG"
          />
        </div>
        <div>
          <img
            src="https://logan.nnnow.com/content/dam/nnnow-project/09-nov-2022/se-11-11-/p-storys/Smashbox_P-story.jpg"
            alt="ProductIMG"
          />
        </div>
        <div>
          <img
            src="https://logan.nnnow.com/content/dam/nnnow-project/09-nov-2022/se-11-11-/p-storys/Nudestix_P-story.jpg"
            alt="ProductIMG"
          />
        </div>
        <div>
          <img
            src="https://logan.nnnow.com/content/dam/nnnow-project/09-nov-2022/se-11-11-/p-storys/Smashbox_P-story.jpg"
            alt="ProductIMG"
          />
        </div>
        <div>
          <img
            src="https://logan.nnnow.com/content/dam/nnnow-project/09-nov-2022/se-11-11-/p-storys/Smashbox_P-story.jpg"
            alt="ProductIMG"
          />
        </div>
        <div>
          <img
            src="https://logan.nnnow.com/content/dam/nnnow-project/09-nov-2022/se-11-11-/p-storys/Olaplex_P-story.jpg"
            alt="ProductIMG"
          />
        </div>
        <div>
          <img
            src="https://logan.nnnow.com/content/dam/nnnow-project/09-nov-2022/se-11-11-/p-storys/Tomford_Pstory.jpg"
            alt="ProductIMG"
          />
        </div>
        <div>
          <img
            src="https://logan.nnnow.com/content/dam/nnnow-project/09-nov-2022/se-11-11-/p-storys/Smashbox_P-story.jpg"
            alt="ProductIMG"
          />
        </div>
        <div>
          <img
            src="https://logan.nnnow.com/content/dam/nnnow-project/09-nov-2022/se-11-11-/p-storys/OUAI_P-story.jpg"
            alt="ProductIMG"
          />
        </div>
        <div>
          <img
            src="https://logan.nnnow.com/content/dam/nnnow-project/09-nov-2022/se-11-11-/p-storys/Briogeo_P-story.jpg"
            alt="ProductIMG"
          />
        </div>
        <div>
          <img
            src="https://logan.nnnow.com/content/dam/nnnow-project/09-nov-2022/se-11-11-/p-storys/Smashbox_P-story.jpg"
            alt="ProductIMG"
          />
        </div>
        <div>
          <img
            src="https://logan.nnnow.com/content/dam/nnnow-project/09-nov-2022/se-11-11-/p-storys/Smashbox_P-story.jpg"
            alt="ProductIMG"
          />
        </div>
        <div>
          <img
            src="https://logan.nnnow.com/content/dam/nnnow-project/09-nov-2022/se-11-11-/p-storys/BeautyBlender_P-story.jpg"
            alt="ProductIMG"
          />
        </div>
        <div>
          <img
            src="https://logan.nnnow.com/content/dam/nnnow-project/09-nov-2022/se-11-11-/p-storys/Smashbox_P-story.jpg"
            alt="ProductIMG"
          />
        </div>
        <div>
          <img
            src="https://logan.nnnow.com/content/dam/nnnow-project/09-nov-2022/se-11-11-/p-storys/Smashbox_P-story.jpg"
            alt="ProductIMG"
          />
        </div>
        <div>
          <img
            src="https://logan.nnnow.com/content/dam/nnnow-project/09-nov-2022/se-11-11-/p-storys/Glamglow_Pstory.jpg"
            alt="ProductIMG"
          />
        </div>
        <div>
          <img
            src="https://logan.nnnow.com/content/dam/nnnow-project/09-nov-2022/se-11-11-/p-storys/PACORABANNE_Pstory.jpg"
            alt="ProductIMG"
          />
        </div>
        <div>
          <img
            src="https://logan.nnnow.com/content/dam/nnnow-project/09-nov-2022/se-11-11-/p-storys/YSL_Pstory.jpg"
            alt="ProductIMG"
          />
        </div>
        <div>
          <img
            src="https://logan.nnnow.com/content/dam/nnnow-project/09-nov-2022/se-11-11-/p-storys/PACORABANNE_Pstory.jpg"
            alt="ProductIMG"
          />
        </div>
        <div>
          <img
            src="https://logan.nnnow.com/content/dam/nnnow-project/09-nov-2022/se-11-11-/p-storys/CAROLINA_Pstory.jpg"
            alt="ProductIMG"
          />
        </div>
        <div>
          <img
            src="https://logan.nnnow.com/content/dam/nnnow-project/09-nov-2022/se-11-11-/p-storys/VERSACE_Pstory.jpg"
            alt="ProductIMG"
          />
        </div>
        <div>
          <img
            src="https://logan.nnnow.com/content/dam/nnnow-project/09-nov-2022/se-11-11-/p-storys/Kora_P-story.jpg"
            alt="ProductIMG"
          />
        </div>
        <div>
          <img
            src="https://logan.nnnow.com/content/dam/nnnow-project/09-nov-2022/se-11-11-/p-storys/Caudalie_P-story.jpg"
            alt="ProductIMG"
          />
        </div>
        <div>
          <img
            src="https://logan.nnnow.com/content/dam/nnnow-project/09-nov-2022/se-11-11-/p-storys/Juicebeauty_P-story.jpg"
            alt="ProductIMG"
          />
        </div>
      </div>
      <button className="btn" >BACK TO TOP </button>
      <Footer/>
    </>
  );
};

export default HomePage;
